scene: abdomen
source_path: data/abdomen_50.pickle
iterations: 20000
position_lr_init: 0.00019
position_lr_final: 0.0000019
position_lr_delay_mult: 0.01
position_lr_max_steps: 20000
feature_lr: 0.002
opacity_lr: 0.008
radiodensity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.001
percent_dense: 0.01
lambda_dssim: 0.2
densification_interval: 200
opacity_reset_interval: 4000
radiodensity_reset_interval: 2000
densify_from_iter: 500
densify_until_iter: 8000
densify_grad_threshold: 0.000026
random_background: False